// components
import Head from 'next/head'
import { Container, Grid, Col } from '../components/layout'

// images
import Image from 'next/image'
import sampleImage from '../../public/img/microsoft.jpg'


export default function Home() {

  return (
    <>
      <HtmlHead />
      <main>
        <Hero />
        {/* <Percobaan1 /> */}
      </main>
    </>
  )
}


/*
 - html head
 - navbar
 - section 123
 - footer
*/

function HtmlHead () {
  return (
    <Head>
      <title>Ngodingo</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  )
}

function Hero () {
  return (
    <section className="w-full">
      <Container>
        <div className="w-full h-screen grid place-content-center">
          <div>
            <h1 className="font-lexend-deca text-display-3 sm:text-display-2 md:text-display-1 font-semibold text-secondary-90 text-center">
              Learn Together, Make <br className='hidden sm:inline' />
              it Flexible
            </h1>
          </div>
          <div className="flex justify-center gap-x-2">
            <div className="w-20 h-9  bg-primary-50"></div>
            <div className="w-20 h-9  bg-primary-50"></div>
          </div>
        </div>
      </Container>
    </section>
  )
}







function Percobaan1 () {
  return (
    <section className="w-full bg-blue-300">

      <Container className="bg-red-300">
        <h1 className="font-lexend-deca text-display-2 font-semibold">Hello World a e</h1>
      </Container>

      <Container className="bg-red-300">
        <Grid>
          <Col className="">
            <div className="w-full h-20 bg-green-300">wk</div>
          </Col>
          <Col className="col-span-4">
            <div className="w-full h-20 bg-green-500">wk</div>
          </Col>
        </Grid>
      </Container>

      <Container>
        <Grid>
          <Col className="col-span-10">
            <Image 
              src={sampleImage} 
              alt="sample image"
              loading="lazy"
            />
          </Col>
        </Grid>
      </Container>

    </section>
  )
}














/*
function Rest () {
  return (
    <>
      <div className={styles.description}>
        <p>
          Get started by editing&nbsp;
          <code className={styles.code}>pages/index.js</code>
        </p>
        <div>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            By{' '}
            <Image
              src="/vercel.svg"
              alt="Vercel Logo"
              className={styles.vercelLogo}
              width={100}
              height={24}
              priority
            />
          </a>
        </div>
      </div>

      <div className={styles.center}>
        <Image
          className={styles.logo}
          src="/next.svg"
          alt="Next.js Logo"
          width={180}
          height={37}
          priority
        />
        <div className={styles.thirteen}>
          <Image
            src="/thirteen.svg"
            alt="13"
            width={40}
            height={31}
            priority
          />
        </div>
      </div>

      <div className={styles.grid}>
        <a
          href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          className={styles.card}
          target="_blank"
          rel="noopener noreferrer"
        >
          <h2 className={inter.className}>
            Docs <span>-&gt;</span>
          </h2>
          <p className={inter.className}>
            Find in-depth information about Next.js features and&nbsp;API.
          </p>
        </a>

        <a
          href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          className={styles.card}
          target="_blank"
          rel="noopener noreferrer"
        >
          <h2 className={inter.className}>
            Learn <span>-&gt;</span>
          </h2>
          <p className={inter.className}>
            Learn about Next.js in an interactive course with&nbsp;quizzes!
          </p>
        </a>

        <a
          href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          className={styles.card}
          target="_blank"
          rel="noopener noreferrer"
        >
          <h2 className={inter.className}>
            Templates <span>-&gt;</span>
          </h2>
          <p className={inter.className}>
            Discover and deploy boilerplate example Next.js&nbsp;projects.
          </p>
        </a>

        <a
          href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          className={styles.card}
          target="_blank"
          rel="noopener noreferrer"
        >
          <h2 className={inter.className}>
            Deploy <span>-&gt;</span>
          </h2>
          <p className={inter.className}>
            Instantly deploy your Next.js site to a shareable URL
            with&nbsp;Vercel.
          </p>
        </a>
      </div>
    </>
  )
}
*/
