// hooks
import { useState } from 'react'

// utilts
import { tidyTw } from '../utilts/tidy-tailwind'

// components
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { Section, Container, Grid, Col } from '../components/layout'
import { Button } from '../components/button'

// images
import teamworkImg from '../../public/img/teamwork.svg'

// icons
import coffeeIcon from '../../public/icons/characteristic/coffee.svg'
import smartIcon from '../../public/icons/characteristic/smart.svg'
import timeIcon from '../../public/icons/characteristic/time.svg'




export default function Home() {
  return (
    <>
      <HtmlHead />
      <main className="scroll-smooth">
        <Navbar />
        <HeroSection />
        <AboutUs />
        <VisiMisi />
        <Characteristic />
        {/* <BlogSection /> */}
        {/* <Projects /> */}
        {/* <Footer /> */}
      </main>
    </>
  )
}


function HtmlHead () {
  return (
    <Head>
      <title>Ngodingo</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  )
}


function Navbar () {
  const [isOpen, setOpen] = useState(false)

  const menus = [
    {
      name: 'About',
      url: '#about',
    },
    {
      name: 'Blog',
      url: '#blog',
    },
    {
      name: 'Portfolio',
      url: '#portfolio',
    },
    {
      name: 'Contact',
      url: '#contact',
    },
  ]

  return (
    <nav className='fixed w-full z-10 bg-white/70 backdrop-blur-md'>
      <Container>
        <div className="flex w-full h-16 justify-between">
          <div className="h-full">
            logo
          </div>
          <div className="h-full flex">
            {menus.map(menu => (
              <Link
                href={menu.url}
                className="block h-full py-4 px-5 group" >
                <span className="text-body-2 text-secondary-90 group-hover:text-accent-50">
                  {menu.name}
                </span>
              </Link>
            ))}
          </div>
          <div className="h-full flex">
            icon
          </div>
        </div>
      </Container>
    </nav>
  )
}


/*
  HERO

  structure:
  ------------------
  -section
    -container
      -div
        -div
          -h1
        -div
          -button
          -button
    -div background
      -div
        -span circle
        -span circle
  ------------------
*/


function HeroSection () {

  const wrapperSize = 'w-full min-h-[480px] h-[85vh] max-h-[768px]'

  return (

    <section className="relative">

        <Container>

            <div 
              className={tidyTw({
                size: wrapperSize,
                layout: 'grid place-content-center pt-[8vh]',
              })}
            >

                <div>

                    <h1 
                      className={tidyTw({
                        typography: {
                          common: 'font-semibold text-secondary-90 text-center',
                          bs: 'text-display-3',
                          sm: 'sm:text-display-2',
                          md: 'md:text-display-1',
                        }
                      })}
                    >
                      Learn Together, Make <br className='hidden sm:inline' />
                      it Flexible
                    </h1>

                </div>

                <div 
                  className={tidyTw({
                    layout: 'flex flex-wrap justify-center gap-x-1 gap-y-2 mt-9',
                  })}
                >

                    <Button 
                      theme="primary" 
                      href="#1"
                      text="Join Us"  
                    />

                      <Button 
                      theme="secondary"  
                      href="#2"
                      text="Learn More" 
                    />

                </div>

            </div>

        </Container>

        <div 
          role="background" 
          className={tidyTw({
            size: wrapperSize,
            layout: {
              position: 'absolute -z-10 top-0',
              display: 'grid place-items-center overflow-hidden',
            }
          })}
        >

            <div 
              className={tidyTw({
                size:'min-w-full',
                layout: {
                  common: 'flex justify-center',
                  md: 'md:items-center md:gap-x-8',
                }
              })}
            >

                <span 
                  role="blurred-circle" 
                  className={tidyTw({
                    size: {
                      bs: 'w-48 h-48',
                      lg: 'lg:w-56 lg:h-56',
                    },
                    style: {
                      shape: 'rounded-full',
                      color: 'bg-primary-50/[.6] blur-2xl',
                    }
                  })}
                />

                <span 
                  role="blurred-circle" 
                  className={tidyTw({
                    size: {
                      bs: 'w-80 h-80',
                      lg: 'lg:w-96 lg:h-96',
                    },
                    style: {
                      shape: 'rounded-full',
                      color: 'bg-accent-50/[.6] blur-3xl',
                    }
                  })}
                />
            
            </div>
        
        </div>

    </section>
  )
}



/*
  ABOUT US

  structure:
  ------------------
  -section
    -container
      -grid
        -col
          -div
            -image
        -col
          -div
            -h2
            -p
            -button
  ------------------
*/


function AboutUs () {

  return (

    <Section id="about" >

        <Container>

            <Grid
              className={tidyTw({
                layout: {
                  common: 'gap-y-8',
                  lg: 'lg:gap-x-5',
                }
              })}
            >
                        
                <Col 
                  className={tidyTw({
                    size: {
                      bs: 'col-span-4',
                      md: 'md:col-span-6 md:col-start-2',
                      lg: 'lg:col-span-6',
                      xl: 'xl:col-span-7',
                    }
                  })} 
                >

                    <div 
                      className={tidyTw({
                        size: {
                          bs: 'max-w-[420px]',
                          md: 'md:max-w-full',
                        },
                        layout: {
                          common: 'm-auto',
                          md: 'md:px-8',
                          lg: 'lg:px-6',
                          xl: 'xl:px-12',
                        }
                      })}
                    >

                        <Image 
                          src={teamworkImg} 
                          alt="teamwork"
                          loading="lazy" 
                          className={tidyTw({
                            size: 'w-full',
                          })}
                        />

                    </div>

                </Col>

                <Col 
                  className={tidyTw({
                    size: {
                      bs: 'col-span-4',
                      sm: 'sm:col-span-8',
                      lg: 'lg:col-span-6',
                      xl: 'xl:col-span-5',
                    }
                  })}
                >

                    <div 
                      className={tidyTw({
                        size: 'w-full h-full',
                        layout: {
                          common: 'grid',
                          bs: 'place-items-center',
                          lg: 'lg:place-items-start lg:place-content-center',
                        },
                        typography: {
                          bs: 'text-center',
                          lg: 'lg:text-left',
                        },
                      })}
                    >

                        <h2 
                          className={tidyTw({
                            typography: {
                              common: 'font-semibold text-secondary-90',
                              bs: 'text-heading-3',
                              lg: 'lg:text-heading-1',
                            }
                          })} 
                        >
                          About Us
                        </h2>

                        <p 
                          className={tidyTw({
                            typography: {
                              common: 'font-normal text-secondary-50',
                              bs: 'text-body-2',
                              lg: 'lg:text-body-1',
                            },
                            layout: 'mt-4',
                          })} 
                        >
                          Ngodingo, sebuah kata yang diambil dari bahasa jawa 
                          yang apabila diartikan dalam bahasa Indonesia 
                          senada dengan ngodinglah! yang sesuai dengan esensi dari 
                          komunitas ini yaitu tentang berkarya melalui coding
                        </p>

                        <Button 
                          href="#" 
                          theme="primary" 
                          text="Learn More" 
                          className={tidyTw({
                            layout: 'mt-7',
                          })}
                        />

                    </div>

                </Col>

            </Grid>

        </Container>

    </Section>

  )
}





function VisiMisi () {
  const visiMisi = {
    visi: 'Membentuk ekosistem mahasiswa yang semangat berkarya melalui coding untuk dapat bermanfaat bagi masyarakat sekitar',
    misi: [
      'Memberikan fasilitas untuk para anggota dapat belajar bersama tentang coding dengan kurikulum yang setara dengan kebutuhan industri',
      'Memberikan peluang untuk para anggota untuk dapat mengimplementasikan keilmuan coding yang telah dipelajari, melalui karya yang muncul dari keresahan masyarakat sekitar, kemudian mensosialisasikan karyanya untuk dapat digunakan',
      'Menyalurkan anggota ke project berbayar untuk dapat mendapat penghasilan dari hasil kerja kerasnya sendiri',
    ]
  }

  return (
    <Section>
      {/**/}
      <Container className="md:hidden">
        <div className="w-full h-full text-center">
          <h2 className="text-heading-3 lg:text-heading-1 font-semibold text-secondary-90">
            Visi dan Misi
          </h2>
        </div>
      </Container>
      {/**/}
      <Container className="mt-4">
        <Grid>
          <Col size="col-span-4 md:col-span-2 lg:col-start-2 lg:col-span-3" className="hidden md:block">
            <div className="w-full h-full relative">
              <span role="stepper-dash-horizontal" className="absolute w-full border-t-[3px] border-dashed border-primary-30 md:top-[15px] lg:top-[23px] -z-10"></span>
              <h2 className="text-heading-3 lg:text-heading-1 font-semibold text-secondary-90 w-max pr-6 bg-white">
                Visi
              </h2>
            </div>
          </Col>
          <Col size="col-span-4 md:col-span-6 lg:col-span-8">
            <div className="w-full h-full relative">
              <span role="stepper-dash-vertical" className="absolute h-full border-l-[3px] border-dashed border-primary-30 left-[15px] lg:left-[23px] -z-10"></span>
              <div className="grid grid-cols-[32px_1fr] lg:grid-cols-[48px_1fr] gap-x-4">
                <span role="stepper-circle" className="grid place-items-center basis-8 w-8 h-8 lg:w-12 lg:h-12 bg-white border-[3px] border-primary-50 rounded-full"></span>
                <p className="text-body-3 lg:text-body-2 font-normal text-secondary-50 pb-5 md:pb-10 lg:pb-14 xl:pb-18">{visiMisi.visi}</p>
              </div>
            </div>
          </Col>
        </Grid>
      </Container>
      {/**/}
      <Container>
        <Grid>
          <Col size="col-span-4 md:col-span-2 lg:col-start-2 lg:col-span-3" className="hidden md:block">
            <div className="w-full h-full relative">
              <span role="stepper-dash-horizontal" className="absolute w-full border-t-[3px] border-dashed border-primary-30 md:top-[15px] lg:top-[23px] -z-10"></span>
              <h2 className="text-heading-3 lg:text-heading-1 font-semibold text-secondary-90 w-max pr-4 bg-white">
                Misi
              </h2>
            </div>
          </Col>
          <Col size="col-span-4 md:col-span-6 lg:col-span-8">
            <div className="w-full h-full relative">
              <span role="stepper-dash-vertical" className="absolute h-full border-l-[3px] border-dashed border-primary-30 left-[15px] lg:left-[23px] -z-10"></span>
              {visiMisi.misi.map((value, i) => (
              <div className="grid grid-cols-[32px_1fr] lg:grid-cols-[48px_1fr] gap-x-4 last:bg-white group" key={i}>
                <span role="stepper-circle" className="grid place-items-center basis-8 w-8 h-8 lg:w-12 lg:h-12 bg-primary-50 rounded-full text-body-3 lg:text-heading-4 font-semibold text-white">{i+1}</span>
                <p className="text-body-3 lg:text-body-2 font-normal text-secondary-50 pb-5 lg:pb-12 group-last:pb-0">{value}</p>
              </div>
              ))}
            </div>
          </Col>
        </Grid>
      </Container>
      {/**/}
    </Section>
  )
}

/*
  CHARACTERISTIC

  structure:
  ------------------
  -section
    -container
      -div
        -div
          -image
          -h3
          -p
        -div
          -image
          -h3
          -p
        -div
          -image
          -h3
          -p
  ------------------
*/
function Characteristic () {

  const characteristics = [
    {
      title: 'Exciting & Fun',
      desc: 'Berkumpul dan berkolaborasi untuk menghasilkan karya yang diharapkan ada nilai manfaat untuk orang lain',
      icon: coffeeIcon,
    },
    {
      title: 'Flexible',
      desc: 'Karena anggotanya adalah mahasiswa, maka jadwal serta agenda kegiatan kedepan juga akan lebih banyak menyesuaikan dengan kesibukan sebagai mahasiswa.',
      icon: timeIcon,
    },
    {
      title: 'Professional & Responsible',
      desc: 'Walaupun status anggota masih mahasiswa, namun kami akan bertanggung jawab dan bersikap profesional atas semua karya dan project yang diamanahkan kepada kami',
      icon: smartIcon,
    }
  ]

  return (
    <Section>

        <Container 
          fluid 
          className={tidyTw({
            style: 'bg-primary-50',
            layout: {
              bs: 'py-16',
              lg: 'lg:py-32'
            }
          })}
        >

            <div 
              className={tidyTw({
                layout: {
                  common: 'flex gap-y-14',
                  bs: 'flex-col items-center',
                  lg: 'lg:flex-row lg:items-start lg:justify-evenly',
                }
              })}
            >
            
                {characteristics.map((value, i) => (
                  <div 
                    key={i}
                    className={tidyTw({
                      size: {
                        common: 'h-max',
                        bs: 'max-w-[380px]',
                        sm: 'sm:max-w-[480px]',
                      },
                      layout: {
                        common: 'grid gap-y-5',
                        bs: 'px-4',
                        lg: 'lg:px-8 basis-1/3',
                      },
                      typography: 'text-center'
                    })}
                  >

                      <Image
                        src={value.icon} 
                        alt="icon" 
                        className={tidyTw({
                          size: {
                            bs: 'w-12 h-12',
                            lg: 'lg:w-[76px] lg:h-[76px]',
                          },
                          layout: 'm-auto'
                        })}
                      />

                      <h3 
                        className={tidyTw({
                          typography: {
                            common: 'font-semibold text-primary-10',
                            bs: 'text-heading-4',
                            lg: 'lg:text-heading-3',
                          }
                        })}
                      >

                          <span 
                            className={tidyTw({
                              lgSize: 'lg:h-24',
                              lgLayout: 'lg:grid lg:place-items-center',
                            })}
                          >
                            {value.title}
                          </span>

                      </h3>

                      <p 
                        className={tidyTw({
                          typography: {
                            common: 'font-normal text-primary-10 opacity-60',
                            bs: 'text-body-3',
                            lg: 'lg:text-body-2',
                          }
                        })}
                      >
                        {value.desc}
                      </p>
                    
                  </div>
                ))}

            </div>

        </Container>

    </Section>
  )

}




function BlogSection () {
  return (
    <section>
    </section>
  )
}






function Test1 () {
  return (
    <section className="w-full bg-blue-300">

      <Container className="bg-red-300">
        <h1 className="text-display-2 font-semibold">Hello World a e</h1>
      </Container>

      <Container className="bg-red-300">
        <Grid>
          <Col className="">
            <div className="w-full h-20 bg-green-300">wk</div>
          </Col>
          <Col className="col-span-4">
            <div className="w-full h-20 bg-green-500">wk</div>
          </Col>
        </Grid>
      </Container>

      <Container>
        <Grid>
          <Col className="col-span-10">
            <Image 
              src={sampleImage} 
              alt="sample image"
              loading="lazy"
            />
          </Col>
        </Grid>
      </Container>

    </section>
  )
}

