// components
import Head from 'next/head'
import { Container, Grid, Col } from '../components/layout'
import { Button } from '../components/button'

// images
import Image from 'next/image'
import sampleImage from '../../public/img/microsoft.jpg'
import teamworkImg from '../../public/img/teamwork.svg'


export default function Home() {

  return (
    <>
      <HtmlHead />
      <main>
        <HeroSection />
        <AboutUsSection />
      </main>
    </>
  )
}


/*
 - html head
 - navbar
 - section 123
 - footer
*/

function HtmlHead () {
  return (
    <Head>
      <title>Ngodingo</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  )
}

function HeroSection () {
  return (
    <section className="relative w-full">

      <Container>
        <div className="w-full h-[90vh] grid place-content-center pt-[8vh]">
          <div>
            <h1 className="font-lexend-deca text-display-3 sm:text-display-2 md:text-display-1 font-semibold text-secondary-90 text-center">
              Learn Together, Make <br className='hidden sm:inline' />
              it Flexible
            </h1>
          </div>
          <div className="flex flex-wrap justify-center gap-x-1 gap-y-2 mt-9">
            <Button theme="primary" text="Join Us" href="#join-us" />
            <Button theme="secondary" text="Learn More" href="#home" />
          </div>
        </div>
      </Container>

      <div id="_background" className="absolute w-full h-[90vh] -z-10 top-0 grid place-items-center overflow-hidden">
        <div className="min-w-full flex justify-center md:items-center md:gap-x-8">
          <div className="w-48 h-48 lg:w-56 lg:h-56 bg-primary-50/[.6] rounded-full blur-2xl"></div>
          <div className="w-80 h-80 lg:w-96 lg:h-96 bg-accent-50/[.6] rounded-full blur-3xl"></div>
        </div>
      </div>

    </section>
  )
}


function AboutUsSection () {
  return (
    <section>
      <Container>
        <Grid className="gap-y-8 lg:gap-x-5">
          <Col className="col-span-4 md:col-span-6 md:col-start-2 lg:col-span-6 xl:col-span-7">
            <div className="w-full sm:px-14 md:px-0 lg:px-6 xl:px-12">
              <Image 
                className="w-full"
                src={teamworkImg} 
                alt="teamwork"
                loading="lazy" />
            </div>
          </Col>
          <Col className="col-span-4 sm:col-span-8 lg:col-span-6 xl:col-span-5">
            <div className="w-full h-full grid place-content-center place-items-center text-center lg:place-items-start lg:text-left ">
              <h2 className="font-lexend-deca text-heading-3 lg:text-heading-1 font-semibold text-secondary-90">
                About Us
              </h2>
              <p className="font-lexend-deca text-body-2 lg:text-body-2 font-normal text-secondary-50 mt-2">
                Ngodingo, sebuah kata yang diambil dari bahasa jawa yang apabila diartikan dalam bahasa Indonesia senada dengan ngodinglah! yang sesuai dengan esensi dari komunitas ini yaitu tentang berkarya melalui coding
              </p>
              <Button href="#" theme="primary" text="Learn More" className="mt-6"/>
            </div>
          </Col>
        </Grid>
      </Container>
    </section>
  )
}




function Test1 () {
  return (
    <section className="w-full bg-blue-300">

      <Container className="bg-red-300">
        <h1 className="font-lexend-deca text-display-2 font-semibold">Hello World a e</h1>
      </Container>

      <Container className="bg-red-300">
        <Grid>
          <Col className="">
            <div className="w-full h-20 bg-green-300">wk</div>
          </Col>
          <Col className="col-span-4">
            <div className="w-full h-20 bg-green-500">wk</div>
          </Col>
        </Grid>
      </Container>

      <Container>
        <Grid>
          <Col className="col-span-10">
            <Image 
              src={sampleImage} 
              alt="sample image"
              loading="lazy"
            />
          </Col>
        </Grid>
      </Container>

    </section>
  )
}

